const API_URL='https://script.google.com/macros/s/AKfycbwS6id18Mk3HIblO1lidUfVFYPmOXoUjwNIEGLSFtBpH47hzs995XH0qlHwLQPo7Ic/exec';
let token=sessionStorage.getItem('ahaToken'),data=null,team=null,pending={},adminTab='results';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const swalTheme={confirmButtonColor:'#176bd1',cancelButtonColor:'#6b7787',showCloseButton:true,reverseButtons:true};
const confirmAction=(title,text,button='ยืนยัน')=>Swal.fire({...swalTheme,icon:'question',title,text,showCancelButton:true,confirmButtonText:button,cancelButtonText:'ยกเลิก'}).then(r=>r.isConfirmed);
const loading=text=>Swal.fire({title:text,allowOutsideClick:false,allowEscapeKey:false,showConfirmButton:false,showCloseButton:false,didOpen:()=>Swal.showLoading()});
const notify=(icon,title,text='')=>Swal.fire({...swalTheme,icon,title,text,timer:1800,showConfirmButton:false});
['username','password'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login();}}));
$('loginForm').addEventListener('submit',e=>{e.preventDefault();login();});
function rpc(method,...args){return new Promise((resolve,reject)=>{const id=crypto.randomUUID(),timer=setTimeout(()=>{delete pending[id];reject(new Error('การเชื่อมต่อหมดเวลา กรุณาลองใหม่'))},35000);pending[id]={resolve,reject,timer};const f=document.createElement('form');f.method='post';f.action=API_URL;f.target='ahaRpcFrame';const x=document.createElement('input');x.type='hidden';x.name='payload';x.value=JSON.stringify({id,method,args,origin:location.origin});f.append(x);document.body.append(f);f.submit();f.remove();});}
addEventListener('message',e=>{const m=e.data;if(!m||!m.ahaRpc||!pending[m.id])return;const p=pending[m.id];clearTimeout(p.timer);delete pending[m.id];m.ok?p.resolve(m.data):p.reject(new Error(m.error||'เกิดข้อผิดพลาด'));});
async function login(){let box=$('loginError'),user=$('username').value.trim(),pass=$('password').value;box.textContent='';if(!user||!pass){box.textContent='กรุณากรอก Username และ Password';return}if(!await confirmAction('ยืนยันการเข้าสู่ระบบ','ต้องการเข้าสู่ระบบด้วยบัญชีนี้หรือไม่','เข้าสู่ระบบ'))return;loading('กำลังเข้าสู่ระบบ…');try{let r=await rpc('login',user,pass);token=r.token;sessionStorage.setItem('ahaToken',token);await load(true);notify('success','เข้าสู่ระบบสำเร็จ')}catch(e){Swal.close();box.textContent=e.message;notify('error','เข้าสู่ระบบไม่สำเร็จ',e.message)}}
function resetSession(){sessionStorage.removeItem('ahaToken');token=null;data=null;$('app').classList.add('hidden');$('loginBox').classList.remove('hidden');$('logout').classList.add('hidden')}
async function logout(){if(!await confirmAction('ยืนยันออกจากระบบ','ต้องการออกจากระบบหรือไม่','ออกจากระบบ'))return;loading('กำลังออกจากระบบ…');resetSession();Swal.close();notify('success','ออกจากระบบแล้ว')}
async function load(keepLoading=false){if(!keepLoading)loading('กำลังโหลดข้อมูล…');try{data=await rpc('getAppData',token);$('loginBox').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');render();Swal.close()}catch(e){Swal.close();resetSession();$('loginError').textContent='Session หมดอายุ กรุณาเข้าสู่ระบบใหม่';notify('error','โหลดข้อมูลไม่สำเร็จ',e.message)}}
function render(){$('content').innerHTML=data.user.role==='admin'?adminView():judgeView()}
function judgeView(){let s=data.myScores||{},n=Object.keys(s).length;return `<div class="stats"><div class="stat"><small>กรรมการ</small><b>${esc(data.user.name)}</b></div><div class="stat"><small>ประเมินแล้ว</small><b>${n}/${data.teams.length}</b></div><div class="stat"><small>เหลือ</small><b>${data.teams.length-n} ทีม</b></div></div><section class="panel"><div class="head"><h2>รายชื่อกลุ่มแข่งขัน</h2><span class="hint">กดให้คะแนนหรือแก้ไขได้ตลอด</span></div>${data.teams.map(t=>`<div class="team"><span class="no">${esc(t.no)}</span><div><b>${esc(t.name)}</b><small>${esc(t.theme)} · ${esc(t.department||'-')}</small></div><div><span class="tag ${s[t.id]?'done':''}">${s[t.id]?'บันทึกแล้ว':'ยังไม่ประเมิน'}</span><button class="alt" onclick="openScore('${esc(t.id)}')">${s[t.id]?'แก้ไข':'ให้คะแนน'}</button></div></div>`).join('')}</section>`}
function adminView(){let r=data.results||[];const tabs=`<nav class="admin-nav"><button class="${adminTab==='results'?'active':''}" onclick="setAdminTab('results')">สรุปผล</button><button class="${adminTab==='teams'?'active':''}" onclick="setAdminTab('teams')">จัดการทีม</button><button class="${adminTab==='users'?'active':''}" onclick="setAdminTab('users')">จัดการผู้ใช้</button></nav>`;const results=`<section class="panel"><div class="head"><h2>สรุปผลคะแนน</h2></div><table><thead><tr><th>อันดับ</th><th>ทีม</th><th class="right">เฉลี่ย</th><th class="right">ประเมินแล้ว</th></tr></thead><tbody>${r.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b><small>${esc(x.theme)}</small></td><td class="right">${(+x.average).toFixed(2)}</td><td class="right">${x.judges}/${data.judgeCount}</td></tr>`).join('')||'<tr><td colspan="4">ยังไม่มีคะแนน</td></tr>'}</tbody></table></section>`;const teams=`<section class="panel"><div class="head"><h2>เพิ่มทีมแข่งขัน</h2><span class="hint">กำหนดลำดับและรหัสทีมอัตโนมัติ</span></div><div class="formrow"><label>ชื่อทีม<input id="tn"></label><label>Theme<input id="tt"></label><label>ผู้นำเสนอ<input id="tp"></label><label>แผนก<input id="td"></label><button onclick="addTeam()">เพิ่มทีม</button></div><div id="teamError" class="error"></div></section>`;const users=`<section class="panel"><div class="head"><h2>เพิ่มผู้ใช้</h2><span class="hint">เพิ่มกรรมการหรือผู้ดูแลระบบ</span></div><div class="formrow"><label>ชื่อ<input id="un"></label><label>Username<input id="uu"></label><label>Password<input id="up" type="password"></label><label>สิทธิ์<select id="ur"><option value="judge">กรรมการ</option><option value="admin">Admin</option></select></label><button onclick="addUser()">เพิ่มผู้ใช้</button></div><div id="userError" class="error"></div></section>`;return `<div class="stats"><div class="stat"><small>ทีมแข่งขัน</small><b>${data.teams.length}</b></div><div class="stat"><small>กรรมการ</small><b>${data.judgeCount}</b></div><div class="stat"><small>รายการคะแนน</small><b>${data.scoreCount}</b></div></div>${tabs}${adminTab==='results'?results:adminTab==='teams'?teams:users}`}
function setAdminTab(tab){adminTab=tab;render()}
function openScore(id){team=data.teams.find(t=>t.id===id);let old=(data.myScores||{})[id]?.ratings||{};$('dialog').innerHTML=`<h2>${esc(team.no)}. ${esc(team.name)}</h2><p class="hint">${esc(team.theme)}</p><div id="total" class="total"></div>${data.criteria.map(c=>`<div class="criterion"><div><h3>${esc(c.no)}. ${esc(c.item)} (${c.weight}%)</h3><p>${esc(c.perspective)}</p></div><div class="scale">${[1,2,3,4,5].map(n=>`<label><input name="c${c.no}" type="radio" value="${n}" ${+old[c.no]===n?'checked':''} onchange="calc()">${n}</label>`).join('')}</div></div>`).join('')}<div class="foot"><button class="alt" onclick="closeScore()">ยกเลิก</button><button onclick="saveScore()">บันทึกคะแนน</button></div>`;$('modal').classList.remove('hidden');calc()}
function closeScore(){$('modal').classList.add('hidden')}
function calc(){let sum=0;data.criteria.forEach(c=>{let q=document.querySelector(`input[name="c${c.no}"]:checked`);if(q)sum+=+q.value/5*c.weight});$('total').textContent=`คะแนนถ่วงน้ำหนัก: ${sum.toFixed(2)} / 100`}
async function saveScore(){let ratings={};for(const c of data.criteria){let q=document.querySelector(`input[name="c${c.no}"]:checked`);if(!q){notify('warning','กรอกคะแนนไม่ครบ','กรุณาเลือกคะแนนให้ครบทุกหัวข้อ');return}ratings[c.no]=+q.value}if(!await confirmAction('ยืนยันการบันทึกคะแนน',`บันทึกคะแนนของทีม ${team.name} หรือไม่`,'บันทึกคะแนน'))return;loading('กำลังบันทึกคะแนน…');try{await rpc('saveScore',token,{teamId:team.id,ratings});closeScore();await load(true);notify('success','บันทึกคะแนนสำเร็จ')}catch(e){Swal.close();notify('error','บันทึกคะแนนไม่สำเร็จ',e.message)}}
async function addTeam(){let box=$('teamError'),payload={name:$('tn').value.trim(),theme:$('tt').value.trim(),presenter:$('tp').value.trim(),department:$('td').value.trim()};box.textContent='';if(!payload.name){box.textContent='กรุณาระบุชื่อทีม';return}if(!await confirmAction('ยืนยันเพิ่มทีม',`เพิ่มทีม “${payload.name}” หรือไม่`,'เพิ่มทีม'))return;loading('กำลังเพิ่มทีม…');try{await rpc('addTeam',token,payload);await load(true);notify('success','เพิ่มทีมสำเร็จ')}catch(e){Swal.close();box.textContent=e.message;notify('error','เพิ่มทีมไม่สำเร็จ',e.message)}}
async function addUser(){let box=$('userError'),payload={name:$('un').value.trim(),username:$('uu').value.trim(),password:$('up').value,role:$('ur').value};box.textContent='';if(!payload.name||!payload.username||!payload.password){box.textContent='กรุณากรอกข้อมูลให้ครบ';return}if(!await confirmAction('ยืนยันเพิ่มผู้ใช้',`เพิ่มผู้ใช้ ${payload.username} หรือไม่`,'เพิ่มผู้ใช้'))return;loading('กำลังเพิ่มผู้ใช้…');try{await rpc('addUser',token,payload);await load(true);notify('success','เพิ่มผู้ใช้สำเร็จ')}catch(e){Swal.close();box.textContent=e.message;notify('error','เพิ่มผู้ใช้ไม่สำเร็จ',e.message)}}
if(token)load();
