const API_URL='https://script.google.com/macros/s/AKfycbyh8Yh1FNYXxbt-JVrokJaljLjCD8Mgu8aC7UER7Z5-I7Z-BN9WQDMLO0iL5KXGJ-4/exec';
let token=sessionStorage.getItem('ahaToken'),data=null,team=null,pending={},adminTab='results',judgeLang=sessionStorage.getItem('ahaJudgeLang')||'en';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const swalTheme={confirmButtonColor:'#176bd1',cancelButtonColor:'#6b7787',showCloseButton:true,reverseButtons:true};
const confirmAction=(title,text,button='ยืนยัน',cancel='ยกเลิก')=>Swal.fire({...swalTheme,icon:'question',title,text,showCancelButton:true,confirmButtonText:button,cancelButtonText:cancel}).then(r=>r.isConfirmed);
const loading=text=>Swal.fire({title:text,allowOutsideClick:false,allowEscapeKey:false,showConfirmButton:false,showCloseButton:false,didOpen:()=>Swal.showLoading()});
const notify=(icon,title,text='')=>Swal.fire({...swalTheme,icon,title,text,timer:1800,showConfirmButton:false});
const JA_CRITERIA={1:{item:'ありたい姿',perspective:'パーパス「化学の力で社会を変える」を実現するために、共創型化学会社としての2030年のチームのありたい姿や未来像を描いている。',score5:'ありたい姿や自分達の未来像が非常に明確である。',score3:'ありたい姿や自分達の未来像が明確である。',score1:'ありたい姿や自分達の未来像が明確になっていない。'},2:{item:'高い目標',perspective:'パーパス実現に向けて今年度高い目標を設定している。',score5:'実現が非常に困難である高い目標を設定している。',score3:'実現が困難である目標を設定している。',score1:'実現が容易である目標を設定している。'},3:{item:'どれだけ挑戦したか',perspective:'目標達成のためにバリューを実践し、どれだけ工夫をしているか、失敗しても挑戦し続けているか？',score5:'多くの工夫をしている。失敗しても何度も挑戦し続けている。',score3:'工夫や挑戦に対し、一定の評価ができる。',score1:'工夫や挑戦が感じられない。'},4:{item:'どう行動が変わったか（行動変容）',perspective:'バリューを実践することで、行動が変わっているか？',score5:'行動変容に繋がっており、チームメンバーの成長に繋がっている。',score3:'行動変容やチームメンバーの成長に繋がっていることに一定の評価ができる。',score1:'行動変容までに至っていない。チームメンバーの成長に繋がっていない。'},5:{item:'目標に対する達成度',perspective:'今年度の目標に対する達成度',score5:'目標を上回る達成をした。',score3:'目標を達成した。',score1:'目標が未達であった。'},6:{item:'共感（論理的）',perspective:'誰もが参考にすべき内容であると認められる',score5:'活動内容を広める価値がある、横展開による効果が大きい。',score3:'活動内容を広める価値や横展開することに対し、一定の評価ができる。',score1:'活動内容を横展開できる範囲が限定的。'},7:{item:'共感（感情的）',perspective:'発表者の思いに共感し広める価値がある',score5:'発表者の思いに共感し広める価値がある。',score3:'共感できる。',score1:'あまり共感できない。'}};
const judgeText=()=>judgeLang==='ja'?{subtitle:'AHAプロジェクト評価システム',signOut:'ログアウト',judge:'審査員',evaluated:'評価済み',remaining:'残り',teams:'チーム',teamList:'チーム一覧',language:'言語',languageHint:'評価基準の表示言語を選択',notScored:'未評価',scored:'保存済み',score:'採点',edit:'編集',guide:'採点の目安',cancel:'キャンセル',save:'採点を保存',total:'加重スコア',incomplete:'入力が不完全です',selectAll:'すべての項目を採点してください。',confirmSave:'採点を保存しますか？',saving:'採点を保存中…',saved:'採点を保存しました',saveError:'採点を保存できませんでした',confirmSignOut:'ログアウトしますか？',signOutPrompt:'現在のセッションを終了します。',signingOut:'ログアウト中…',signedOut:'ログアウトしました'}:{subtitle:'AHA Project Evaluation System',signOut:'Sign out',judge:'Judge',evaluated:'Evaluated',remaining:'Remaining',teams:'teams',teamList:'Competition teams',language:'Language',languageHint:'Choose the language used for scoring criteria',notScored:'Not evaluated',scored:'Saved',score:'Score',edit:'Edit',guide:'Scoring guide',cancel:'Cancel',save:'Save score',total:'Weighted score',incomplete:'Incomplete scoring',selectAll:'Please select a score for every criterion.',confirmSave:'Save this team’s score?',saving:'Saving score…',saved:'Score saved',saveError:'Unable to save score',confirmSignOut:'Confirm sign out',signOutPrompt:'End the current session?',signingOut:'Signing out…',signedOut:'Signed out'};
function evaluationTarget(no){const target=no<=2?{key:'goal',weight:20}:no<=4?{key:'process',weight:40}:no===5?{key:'results',weight:20}:{key:'relatability',weight:20};const names=judgeLang==='ja'?{goal:'目標',process:'プロセス',results:'成果',relatability:'共感'}:{goal:'Goal',process:'Process',results:'Results',relatability:'Relatability'};const heading=judgeLang==='ja'?'評価対象':'Evaluation Target';return{...target,name:names[target.key],heading};}
['username','password'].forEach(id=>$(id).addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();login();}}));
$('loginForm').addEventListener('submit',e=>{e.preventDefault();login();});
function rpc(method,...args){return new Promise((resolve,reject)=>{const id=crypto.randomUUID(),timer=setTimeout(()=>{delete pending[id];reject(new Error('การเชื่อมต่อหมดเวลา กรุณาลองใหม่'))},35000);pending[id]={resolve,reject,timer};const f=document.createElement('form');f.method='post';f.action=API_URL;f.target='ahaRpcFrame';const x=document.createElement('input');x.type='hidden';x.name='payload';x.value=JSON.stringify({id,method,args,origin:location.origin});f.append(x);document.body.append(f);f.submit();f.remove();});}
addEventListener('message',e=>{const m=e.data;if(!m||!m.ahaRpc||!pending[m.id])return;const p=pending[m.id];clearTimeout(p.timer);delete pending[m.id];m.ok?p.resolve(m.data):p.reject(new Error(m.error||'เกิดข้อผิดพลาด'));});
async function login(){let box=$('loginError'),user=$('username').value.trim(),pass=$('password').value;box.textContent='';if(!user||!pass){box.textContent='Please enter your username and password.';return}if(!await confirmAction('Confirm sign in','Sign in with this account?','Sign in','Cancel'))return;loading('Signing in…');try{let r=await rpc('login',user,pass);token=r.token;sessionStorage.setItem('ahaToken',token);await load(true);notify('success','Signed in successfully')}catch(e){Swal.close();box.textContent=e.message;notify('error','Sign in failed',e.message)}}
function resetSession(){sessionStorage.removeItem('ahaToken');token=null;data=null;$('app').classList.add('hidden');$('loginBox').classList.remove('hidden');$('logout').classList.add('hidden');$('headerSubtitle').textContent='AHA Project Evaluation System';$('logout').textContent='Sign out'}
async function logout(){const t=data?.user?.role==='judge'?judgeText():{confirmSignOut:'ยืนยันออกจากระบบ',signOutPrompt:'ต้องการออกจากระบบหรือไม่',signOut:'ออกจากระบบ',cancel:'ยกเลิก',signingOut:'กำลังออกจากระบบ…',signedOut:'ออกจากระบบแล้ว'};if(!await confirmAction(t.confirmSignOut,t.signOutPrompt,t.signOut,t.cancel))return;loading(t.signingOut);resetSession();Swal.close();notify('success',t.signedOut)}
async function load(keepLoading=false){if(!keepLoading)loading('กำลังโหลดข้อมูล…');try{data=await rpc('getAppData',token);$('loginBox').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');render();Swal.close()}catch(e){Swal.close();resetSession();$('loginError').textContent='Your session has expired. Please sign in again.';notify('error','Unable to load data',e.message)}}
function render(){if(data.user.role==='admin'){$('content').innerHTML=adminView();return}const t=judgeText();$('headerSubtitle').textContent=t.subtitle;$('logout').textContent=t.signOut;$('content').innerHTML=judgeView()}
function judgeView(){let s=data.myScores||{},n=Object.keys(s).length,t=judgeText();return `<div class="stats"><div class="stat"><small>${t.judge}</small><b>${esc(data.user.name)}</b></div><div class="stat"><small>${t.evaluated}</small><b>${n}/${data.teams.length}</b></div><div class="stat"><small>${t.remaining}</small><b>${data.teams.length-n} ${t.teams}</b></div></div><section class="panel"><div class="head"><h2>${t.teamList}</h2><label class="language-select">${t.language}<select onchange="setJudgeLanguage(this.value)"><option value="en" ${judgeLang==='en'?'selected':''}>English</option><option value="ja" ${judgeLang==='ja'?'selected':''}>日本語</option></select></label></div><span class="hint">${t.languageHint}</span>${data.teams.map(x=>`<div class="team"><span class="no">${esc(x.no)}</span><div><b>${esc(x.name)}</b><small>${esc(x.theme)} · ${esc(x.department||'-')}</small></div><div><span class="tag ${s[x.id]?'done':''}">${s[x.id]?t.scored:t.notScored}</span><button class="alt" onclick="openScore('${esc(x.id)}')">${s[x.id]?t.edit:t.score}</button></div></div>`).join('')}</section>`}
function setJudgeLanguage(language){judgeLang=language==='ja'?'ja':'en';sessionStorage.setItem('ahaJudgeLang',judgeLang);render()}
function adminView(){let r=data.results||[];const tabs=`<nav class="admin-nav"><button class="${adminTab==='results'?'active':''}" onclick="setAdminTab('results')">สรุปผล</button><button class="${adminTab==='teams'?'active':''}" onclick="setAdminTab('teams')">จัดการทีม</button><button class="${adminTab==='users'?'active':''}" onclick="setAdminTab('users')">จัดการผู้ใช้</button></nav>`;const results=`<section class="panel"><div class="head"><h2>สรุปผลคะแนน</h2></div><table><thead><tr><th>อันดับ</th><th>ทีม</th><th class="right">เฉลี่ย</th><th class="right">ประเมินแล้ว</th></tr></thead><tbody>${r.map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b><small>${esc(x.theme)}</small></td><td class="right">${(+x.average).toFixed(2)}</td><td class="right">${x.judges}/${data.judgeCount}</td></tr>`).join('')||'<tr><td colspan="4">ยังไม่มีคะแนน</td></tr>'}</tbody></table></section>`;const teams=`<section class="panel"><div class="head"><h2>เพิ่มทีมแข่งขัน</h2><span class="hint">กำหนดลำดับและรหัสทีมอัตโนมัติ</span></div><div class="formrow"><label>ชื่อทีม<input id="tn"></label><label>Theme<input id="tt"></label><label>ผู้นำเสนอ<input id="tp"></label><label>แผนก<input id="td"></label><button onclick="addTeam()">เพิ่มทีม</button></div><div id="teamError" class="error"></div></section>`;const users=`<section class="panel"><div class="head"><h2>เพิ่มผู้ใช้</h2><span class="hint">เพิ่มกรรมการหรือผู้ดูแลระบบ</span></div><div class="formrow"><label>ชื่อ<input id="un"></label><label>Username<input id="uu"></label><label>Password<input id="up" type="password"></label><label>สิทธิ์<select id="ur"><option value="judge">กรรมการ</option><option value="admin">Admin</option></select></label><button onclick="addUser()">เพิ่มผู้ใช้</button></div><div id="userError" class="error"></div></section>`;return `<div class="stats"><div class="stat"><small>ทีมแข่งขัน</small><b>${data.teams.length}</b></div><div class="stat"><small>กรรมการ</small><b>${data.judgeCount}</b></div><div class="stat"><small>รายการคะแนน</small><b>${data.scoreCount}</b></div></div>${tabs}${adminTab==='results'?results:adminTab==='teams'?teams:users}`}
function setAdminTab(tab){adminTab=tab;render()}
function openScore(id){team=data.teams.find(t=>t.id===id);let old=(data.myScores||{})[id]?.ratings||{},t=judgeText();const criterionCard=c=>{const d=judgeLang==='ja'?{...c,...JA_CRITERIA[c.no]}:c,guides=[5,4,3,2,1].filter(n=>d['score'+n]).map(n=>`<p><b>${t.score} ${n}:</b> ${esc(d['score'+n])}</p>`).join('');return `<div class="criterion"><div><h3>${esc(c.no)}. ${esc(d.item)} (${c.weight}%)</h3><p>${esc(d.perspective)}</p></div><div class="scale">${[1,2,3,4,5].map(n=>`<label title="${esc(d['score'+n]||'')}"><input name="c${c.no}" type="radio" value="${n}" ${+old[c.no]===n?'checked':''} onchange="calc()">${n}</label>`).join('')}</div>${guides?`<details class="score-guide"><summary>${t.guide}</summary>${guides}</details>`:''}</div>`};const groups=[1,3,5,6].map(no=>evaluationTarget(no)).map(target=>`<section class="target-card"><div class="target-card-head"><span>${target.heading}</span><b>${target.name}</b><em>${target.weight}%</em></div><div class="target-criteria">${data.criteria.filter(c=>evaluationTarget(c.no).key===target.key).map(criterionCard).join('')}</div></section>`).join('');const html=`<div class="score-page"><div class="score-title"><h2>${esc(team.no)}. ${esc(team.name)}</h2><p>${esc(team.theme)}</p></div><div id="total" class="total"></div><div class="criteria-list">${groups}</div><div class="foot"><button class="alt" onclick="closeScore()">${t.cancel}</button><button onclick="saveScore()">${t.save}</button></div></div>`;Swal.fire({...swalTheme,html,showConfirmButton:false,showCloseButton:true,allowOutsideClick:false,allowEscapeKey:false,customClass:{popup:'score-swal-popup',htmlContainer:'score-swal-html'}});setTimeout(calc,0)}
function closeScore(){Swal.close()}
function calc(){let sum=0;data.criteria.forEach(c=>{let q=document.querySelector(`input[name="c${c.no}"]:checked`);if(q)sum+=+q.value/5*c.weight});$('total').textContent=`${judgeText().total}: ${sum.toFixed(2)} / 100`}
async function saveScore(){let ratings={},t=judgeText();for(const c of data.criteria){let q=document.querySelector(`input[name="c${c.no}"]:checked`);if(!q){notify('warning',t.incomplete,t.selectAll);return}ratings[c.no]=+q.value}if(!await confirmAction(t.confirmSave,team.name,t.save,t.cancel))return;loading(t.saving);try{await rpc('saveScore',token,{teamId:team.id,ratings});await load(true);notify('success',t.saved)}catch(e){Swal.close();notify('error',t.saveError,e.message)}}
async function addTeam(){let box=$('teamError'),payload={name:$('tn').value.trim(),theme:$('tt').value.trim(),presenter:$('tp').value.trim(),department:$('td').value.trim()};box.textContent='';if(!payload.name){box.textContent='กรุณาระบุชื่อทีม';return}if(!await confirmAction('ยืนยันเพิ่มทีม',`เพิ่มทีม “${payload.name}” หรือไม่`,'เพิ่มทีม'))return;loading('กำลังเพิ่มทีม…');try{await rpc('addTeam',token,payload);await load(true);notify('success','เพิ่มทีมสำเร็จ')}catch(e){Swal.close();box.textContent=e.message;notify('error','เพิ่มทีมไม่สำเร็จ',e.message)}}
async function addUser(){let box=$('userError'),payload={name:$('un').value.trim(),username:$('uu').value.trim(),password:$('up').value,role:$('ur').value};box.textContent='';if(!payload.name||!payload.username||!payload.password){box.textContent='กรุณากรอกข้อมูลให้ครบ';return}if(!await confirmAction('ยืนยันเพิ่มผู้ใช้',`เพิ่มผู้ใช้ ${payload.username} หรือไม่`,'เพิ่มผู้ใช้'))return;loading('กำลังเพิ่มผู้ใช้…');try{await rpc('addUser',token,payload);await load(true);notify('success','เพิ่มผู้ใช้สำเร็จ')}catch(e){Swal.close();box.textContent=e.message;notify('error','เพิ่มผู้ใช้ไม่สำเร็จ',e.message)}}
if(token)load();
